' Generated by install-clinix.ps1 - starts the Clinix server with no window.
' Regenerated every time the installer runs; edit the installer, not this file.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "D:\Clinix\Clinix\backend"
sh.Run "cmd /c """"C:\Program Files\nodejs\node.exe"" src\server.js > ""D:\Clinix\Clinix\backend\clinix-server.log"" 2>&1""", 0, False
