// ── Turning report data into a file somebody can hand in ─────────────────────
// The export dialog offered CSV, Excel and PDF long before any of them did
// anything. This module is the part that was missing.
//
// Deliberately dependency-free. A clinic PC that has gone a week without
// internet still has to be able to produce the monthly report, and adding a
// spreadsheet library to do what amounts to writing XML into a zip would put
// three megabytes into the bundle for it.

export type ReportCell = string | number;

export type ReportTable = {
  /** Sheet/section name. Kept short — Excel refuses sheet names over 31 chars. */
  title: string;
  columns: string[];
  rows: ReportCell[][];
};

export type ReportMeta = {
  /** e.g. "This Month" or "1 Aug 2026 – 10 Aug 2026" */
  period: string;
  generatedAt: Date;
  generatedBy: string;
};

// ── CSV ──────────────────────────────────────────────────────────────────────

/**
 * A field is quoted when it contains a comma, a quote or a newline, and inner
 * quotes are doubled — the rules every spreadsheet agrees on. A medicine called
 * `Paracetamol 500mg, 10s` breaks the file without this.
 */
function csvField(value: ReportCell): string {
  const s = String(value ?? '');
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(tables: ReportTable[], meta: ReportMeta): string {
  const lines: string[] = [
    `Clinix Report`,
    `Period,${csvField(meta.period)}`,
    `Generated,${csvField(meta.generatedAt.toLocaleString())}`,
    `Generated by,${csvField(meta.generatedBy)}`,
  ];
  for (const t of tables) {
    lines.push('', t.title, t.columns.map(csvField).join(','));
    for (const row of t.rows) lines.push(row.map(csvField).join(','));
    if (!t.rows.length) lines.push('(no records for this period)');
  }
  // Excel reads a bare UTF-8 CSV as the system codepage and turns "ñ" into
  // mojibake. The byte-order mark is what tells it otherwise.
  return '﻿' + lines.join('\r\n');
}

// ── XLSX ─────────────────────────────────────────────────────────────────────
// An .xlsx is a zip of XML parts. Both halves are written by hand below: the
// XML because it is short, and the zip with no compression because "store" is a
// legal deflate method and skipping compression skips needing a deflate
// implementation. The result is a genuine xlsx — Excel opens it with no
// format-mismatch warning, which is the whole reason not to just rename a CSV.

const XML_ESCAPES: Record<string, string> = {
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;',
};

function xmlEscape(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => XML_ESCAPES[ch]);
}

/** Excel rejects these characters in a sheet name, and truncates past 31. */
function safeSheetName(title: string, index: number): string {
  const cleaned = title.replace(/[[\]:*?/\\]/g, ' ').trim().slice(0, 31);
  return cleaned || `Sheet${index + 1}`;
}

/** 0 → 'A', 25 → 'Z', 26 → 'AA' — the spreadsheet column naming. */
function columnName(index: number): string {
  let n = index;
  let name = '';
  do {
    name = String.fromCharCode(65 + (n % 26)) + name;
    n = Math.floor(n / 26) - 1;
  } while (n >= 0);
  return name;
}

function sheetXml(table: ReportTable): string {
  const rowXml = (cells: ReportCell[], rowIndex: number) => {
    const parts = cells.map((cell, colIndex) => {
      const ref = `${columnName(colIndex)}${rowIndex + 1}`;
      // A number stays a number so the recipient can total a column. Anything
      // else goes out as an inline string, which avoids a shared-string table.
      if (typeof cell === 'number' && Number.isFinite(cell)) {
        return `<c r="${ref}"><v>${cell}</v></c>`;
      }
      return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(String(cell ?? ''))}</t></is></c>`;
    });
    return `<row r="${rowIndex + 1}">${parts.join('')}</row>`;
  };

  const all = [table.columns as ReportCell[], ...table.rows];
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">`
    + `<sheetData>${all.map(rowXml).join('')}</sheetData>`
    + `</worksheet>`;
}

function buildXlsxParts(tables: ReportTable[]): { name: string; content: string }[] {
  const names = tables.map((t, i) => safeSheetName(t.title, i));

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">`
    + `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>`
    + `<Default Extension="xml" ContentType="application/xml"/>`
    + `<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`
    + tables.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')
    + `</Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">`
    + `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>`
    + `</Relationships>`;

  const workbook = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" `
    + `xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">`
    + `<sheets>${names.map((n, i) => `<sheet name="${xmlEscape(n)}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join('')}</sheets>`
    + `</workbook>`;

  const workbookRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">`
    + tables.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join('')
    + `</Relationships>`;

  return [
    { name: '[Content_Types].xml', content: contentTypes },
    { name: '_rels/.rels', content: rootRels },
    { name: 'xl/workbook.xml', content: workbook },
    { name: 'xl/_rels/workbook.xml.rels', content: workbookRels },
    ...tables.map((t, i) => ({ name: `xl/worksheets/sheet${i + 1}.xml`, content: sheetXml(t) })),
  ];
}

// ── The smallest zip that is still a zip ─────────────────────────────────────

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
    table[i] = c >>> 0;
  }
  return table;
})();

function crc32(bytes: Uint8Array): number {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < bytes.length; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

/** MS-DOS date/time, which is what a zip entry records. */
function dosDateTime(d: Date): { time: number; date: number } {
  return {
    time: (d.getHours() << 11) | (d.getMinutes() << 5) | (Math.floor(d.getSeconds() / 2)),
    date: ((d.getFullYear() - 1980) << 9) | ((d.getMonth() + 1) << 5) | d.getDate(),
  };
}

function zipStore(files: { name: string; content: string }[], when: Date): Blob {
  const encoder = new TextEncoder();
  const { time, date } = dosDateTime(when);
  const chunks: Uint8Array[] = [];
  const central: Uint8Array[] = [];
  let offset = 0;

  const u16 = (v: number) => [v & 0xFF, (v >>> 8) & 0xFF];
  const u32 = (v: number) => [v & 0xFF, (v >>> 8) & 0xFF, (v >>> 16) & 0xFF, (v >>> 24) & 0xFF];

  for (const file of files) {
    const nameBytes = encoder.encode(file.name);
    const data = encoder.encode(file.content);
    const crc = crc32(data);

    const localHeader = new Uint8Array([
      ...u32(0x04034b50),      // local file header signature
      ...u16(20),              // version needed
      ...u16(0),               // flags
      ...u16(0),               // method 0 = stored
      ...u16(time), ...u16(date),
      ...u32(crc),
      ...u32(data.length),     // compressed size == uncompressed, being stored
      ...u32(data.length),
      ...u16(nameBytes.length),
      ...u16(0),               // extra field length
    ]);

    chunks.push(localHeader, nameBytes, data);

    central.push(new Uint8Array([
      ...u32(0x02014b50),      // central directory header signature
      ...u16(20),              // version made by
      ...u16(20),              // version needed
      ...u16(0), ...u16(0),    // flags, method
      ...u16(time), ...u16(date),
      ...u32(crc),
      ...u32(data.length), ...u32(data.length),
      ...u16(nameBytes.length),
      ...u16(0), ...u16(0),    // extra, comment
      ...u16(0), ...u16(0),    // disk number, internal attrs
      ...u32(0),               // external attrs
      ...u32(offset),          // offset of local header
      ...Array.from(nameBytes),
    ]));

    offset += localHeader.length + nameBytes.length + data.length;
  }

  const centralSize = central.reduce((n, c) => n + c.length, 0);
  const end = new Uint8Array([
    ...u32(0x06054b50),        // end of central directory
    ...u16(0), ...u16(0),      // disk numbers
    ...u16(files.length), ...u16(files.length),
    ...u32(centralSize),
    ...u32(offset),
    ...u16(0),                 // comment length
  ]);

  return new Blob([...chunks, ...central, end], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

export function toXlsx(tables: ReportTable[], meta: ReportMeta): Blob {
  // The cover sheet carries what the file is and when it was taken, so a
  // spreadsheet that has been emailed on still says what period it covers.
  const cover: ReportTable = {
    title: 'Report Info',
    columns: ['Field', 'Value'],
    rows: [
      ['Report', 'Clinix Report'],
      ['Period', meta.period],
      ['Generated', meta.generatedAt.toLocaleString()],
      ['Generated by', meta.generatedBy],
      ['Sections', tables.map((t) => t.title).join(', ')],
    ],
  };
  return zipStore(buildXlsxParts([cover, ...tables]), meta.generatedAt);
}

// ── PDF, via the browser's own print engine ──────────────────────────────────
// There is no PDF library here for the same reason there is no spreadsheet one.
// Every browser can already write a PDF; "Save as PDF" in the print dialog is
// that engine, and it handles page breaks, margins and fonts properly.

export function toPrintHtml(tables: ReportTable[], meta: ReportMeta): string {
  const table = (t: ReportTable) => `
    <section>
      <h2>${xmlEscape(t.title)}</h2>
      ${t.rows.length === 0
        ? `<p class="empty">No records for this period.</p>`
        : `<table>
            <thead><tr>${t.columns.map((c) => `<th>${xmlEscape(c)}</th>`).join('')}</tr></thead>
            <tbody>${t.rows.map((r) => `<tr>${r.map((cell) => `<td>${xmlEscape(String(cell ?? ''))}</td>`).join('')}</tr>`).join('')}</tbody>
          </table>`}
    </section>`;

  return `<!doctype html><html><head><meta charset="utf-8"><title>Clinix Report</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: system-ui, "Segoe UI", Arial, sans-serif; color: #0B1437; margin: 24px; }
    h1 { font-size: 20px; margin: 0 0 4px; }
    .meta { font-size: 12px; color: #64748B; margin-bottom: 20px; }
    .meta span { margin-right: 16px; }
    h2 { font-size: 14px; margin: 22px 0 8px; padding-bottom: 6px; border-bottom: 2px solid #37479A; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th { background: #EEF1FA; text-align: left; padding: 6px 8px; border: 1px solid #DEE3F5; font-weight: 600; }
    td { padding: 5px 8px; border: 1px solid #DEE3F5; }
    tbody tr:nth-child(even) { background: #F7F9FD; }
    .empty { font-size: 12px; color: #64748B; font-style: italic; }
    /* A section should not be split across pages when it can be avoided, and a
       table that does split has to repeat its header or the second page is
       unreadable. */
    section { break-inside: auto; }
    thead { display: table-header-group; }
    tr { break-inside: avoid; }
    @page { margin: 14mm; }
  </style></head><body>
    <h1>Clinix — Clinic Report</h1>
    <div class="meta">
      <span><strong>Period:</strong> ${xmlEscape(meta.period)}</span>
      <span><strong>Generated:</strong> ${xmlEscape(meta.generatedAt.toLocaleString())}</span>
      <span><strong>By:</strong> ${xmlEscape(meta.generatedBy)}</span>
    </div>
    ${tables.map(table).join('')}
  </body></html>`;
}

/**
 * Print the given HTML from a hidden iframe.
 *
 * An iframe rather than window.open because a popup blocker will silently eat
 * the second one, and the user would be left pressing a button that does
 * nothing — which is the bug this whole module exists to fix.
 */
export function printHtml(html: string): void {
  const frame = document.createElement('iframe');
  frame.setAttribute('aria-hidden', 'true');
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;';
  document.body.appendChild(frame);

  const cleanup = () => {
    // Firefox needs the frame to outlive the print dialog; a timeout covers
    // every browser without having to detect which one this is.
    window.setTimeout(() => frame.remove(), 1000);
  };

  frame.onload = () => {
    try {
      const win = frame.contentWindow;
      if (!win) { frame.remove(); return; }
      win.focus();
      win.print();
    } finally {
      cleanup();
    }
  };

  const doc = frame.contentDocument;
  if (!doc) { frame.remove(); return; }
  doc.open();
  doc.write(html);
  doc.close();
}

// ── Download ─────────────────────────────────────────────────────────────────

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoking immediately can cancel the download in some browsers; one turn of
  // the event loop is enough for the click to have been taken.
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}

export function reportFilename(ext: string, when: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `clinix-report-${when.getFullYear()}-${pad(when.getMonth() + 1)}-${pad(when.getDate())}.${ext}`;
}
